name: Bug Report
description: Report a reproducible problem or unexpected behavior in Tutera
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        
        Thanks for taking the time to report a bug and help improve Tutera! Please fill out the form below with as much detail as possible.
        
        > **Note**: If you're reporting a security vulnerability, please do not file a public issue. Instead, follow our [Security Policy](https://github.com/tutera-org/tutera/security).
        
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short description of the bug.
      placeholder: e.g. "Clicking Save on the profile page throws a 500 error"
    validations:
      required: true
      
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the issue.
      placeholder: |
        1. Go to the creator dashboard
        2. Click on "Course Management"
        3. Try to create a new course
        4. Fill in the course details and click "Save"
        5. See the error appear
      render: markdown
    validations:
      required: true
      
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: The course should be saved successfully and redirect to the course management page.
    validations:
      required: true
      
  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happened.
      placeholder: A 500 Internal Server Error is thrown and the course is not saved.
    validations:
      required: true
      
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Details about your environment.
      placeholder: |
        - **App**: tutera-frontend v0.1.0 / tutera-backend v1.0.0
        - **OS**: macOS 14.2 / Ubuntu 24.04 / Windows 11
        - **Browser**: Chrome 130 / Safari 18 / Firefox 119
        - **Node.js**: 18.19.0
        - **MongoDB**: 6.0.12
        - **Redis**: 7.2.3
        - **Deployment**: Local development / Production
      render: markdown
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: Logs, Stack Traces, or Screenshots
      description: Paste any relevant logs, errors, or add screenshots to help explain your problem.
      placeholder: |
        **Browser Console Error:**
        ```
        POST /api/v1/courses 500 (Internal Server Error)
        TypeError: Cannot read properties of undefined (reading 'title')
        ```
        
        **Backend Logs:**
        ```
        ERROR [2024-01-15 10:30:45] TypeError: Cannot read properties of undefined (reading 'title')
        at CourseController.createCourse (/app/src/controllers/courseController.js:45:15)
        ```
      render: shell
      
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of Tutera is affected?
      options:
        - Frontend (tutera-frontend)
        - Backend (tutera-backend)
        - API
        - Database
        - Authentication
        - Media Upload
        - Email Service
        - Other
    validations:
      required: true
      
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical - Blocks core functionality
        - High - Major feature broken
        - Medium - Feature partially broken
        - Low - Minor issue or cosmetic
    validations:
      required: true
      
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: |
        - This started happening after the latest update
        - Only affects users with the "creator" role
        - Works fine in Firefox but not in Chrome
        - Related to issue #123
      render: markdown
      
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      description: Please confirm the following before submitting.
      options:
        - label: I have searched the existing issues for duplicates.
          required: true
        - label: I am not reporting a security vulnerability (those should follow the SECURITY policy).
          required: true
        - label: I have provided enough information to reproduce the issue.
          required: true
        - label: I have included relevant logs, screenshots, or error messages.
          required: false
          
  - type: markdown
    attributes:
      value: |
        ---
        
        🎓 **Thank you for helping improve Tutera!**
        
        We'll review your bug report as soon as possible and work on a fix. If you need to add more information later, you can edit your issue.
